# Generated by Django 3.1.5 on 2021-01-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passesngers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passesngers',
            new_name='passengers',
        ),
    ]
