# Generated by Django 3.1.5 on 2021-01-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20210111_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='flights',
            new_name='flights6',
        ),
    ]
